# Generated by Django 2.1 on 2019-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='体重')),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='BMI')),
                ('fat_rate', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='体脂率')),
                ('xiongwei', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='胸围')),
                ('biwei', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='臂围')),
                ('jiankaun', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='肩宽')),
                ('yaowei', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='腰围')),
                ('tunwei', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='臀围')),
                ('datuiwei', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='腿围')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
